#!/usr/bin/env node
// Self-host the Google Fonts the site depends on, so in-app mobile browsers
// (Instagram/Facebook/WhatsApp webviews) that block or throttle fonts.gstatic.com
// stop rendering with the fallback face or hanging on first paint.
//
// What it does, reproducibly:
//   1. Ask Google Fonts css2 for every family+weight the site uses.
//   2. Keep ONLY the `hebrew` and `latin` subset @font-face blocks (the site is
//      Hebrew with some Latin; latin-ext/math/symbols are dead weight).
//   3. Download each unique woff2 into site/assets/fonts/.
//   4. Emit site/assets/fonts/fonts.css with the src rewritten to local paths,
//      unicode-range preserved so the browser still lazy-loads only what a page
//      actually renders.
//
// Run: node scripts/fetch-fonts.mjs   (re-run to refresh; output is deterministic)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = path.join(ROOT, 'site', 'assets', 'fonts');
const CSS_OUT = path.join(OUT_DIR, 'fonts.css');

// The full set of families/weights referenced anywhere under site/. Heebo is the
// union of every weight any page requests (300..900); Assistant is the body face.
// The rest are page-local decorative faces (options wizard, timer).
const FAMILIES = [
  'Assistant:wght@200;400;500;600',
  'Heebo:wght@300;400;500;600;700;800;900',
  'Fredoka:wght@400;500',
  'Gveret+Levin',
  'Playpen+Sans+Hebrew:wght@400;500',
  'Carlito:wght@400;700',
];
const KEEP_SUBSETS = new Set(['hebrew', 'latin']);
// A recent desktop Chrome UA makes css2 return woff2 (the smallest format).
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

async function main() {
  const url =
    'https://fonts.googleapis.com/css2?' +
    FAMILIES.map((f) => 'family=' + f).join('&') +
    '&display=swap';
  const css = await (await fetch(url, { headers: { 'User-Agent': UA } })).text();
  if (!css.includes('@font-face'))
    throw new Error('css2 returned no @font-face — bad UA or family?');

  fs.mkdirSync(OUT_DIR, { recursive: true });

  // css2 groups each @font-face under a `/* subset */` comment. Walk the file,
  // tracking the current subset label, and rebuild each block we keep.
  const blocks = css.split('@font-face').slice(1);
  // Re-read the comment that PRECEDES each @font-face by splitting on comments too.
  const labelled = [];
  const re = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g;
  let m;
  while ((m = re.exec(css))) labelled.push({ subset: m[1], body: m[2] });
  if (!labelled.length) throw new Error('could not parse subset-labelled @font-face blocks');

  const seen = new Map(); // remote woff2 url -> local filename
  const outFaces = [];
  let kept = 0;
  for (const { subset, body } of labelled) {
    if (!KEEP_SUBSETS.has(subset)) continue;
    const urlMatch = body.match(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2)\)/);
    if (!urlMatch) continue;
    const remote = urlMatch[1];
    let local = seen.get(remote);
    if (!local) {
      const fam = (body.match(/font-family:\s*'([^']+)'/) || [])[1] || 'font';
      const wght = (body.match(/font-weight:\s*(\d+)/) || [])[1] || '400';
      const slug = fam.toLowerCase().replace(/[^a-z0-9]+/g, '-');
      local = `${slug}-${wght}-${subset}.woff2`;
      const buf = Buffer.from(
        await (await fetch(remote, { headers: { 'User-Agent': UA } })).arrayBuffer()
      );
      // woff2 magic 'wOF2' (0x774F4632) — guard against an HTML error page.
      if (buf.length < 4 || buf.toString('latin1', 0, 4) !== 'wOF2')
        throw new Error(`not a woff2: ${remote}`);
      fs.writeFileSync(path.join(OUT_DIR, local), buf);
      seen.set(remote, local);
    }
    const rewritten = body.replace(remote, `/assets/fonts/${local}`).trim();
    outFaces.push(`/* ${subset} */\n@font-face {\n  ${rewritten}\n}`);
    kept++;
  }

  const header =
    '/* Self-hosted Google Fonts (hebrew + latin subsets only).\n' +
    ' * Generated by scripts/fetch-fonts.mjs — do not hand-edit; re-run the script.\n' +
    ` * Families: ${FAMILIES.map((f) => f.split(':')[0].replace(/\+/g, ' ')).join(', ')} */\n\n`;
  fs.writeFileSync(CSS_OUT, header + outFaces.join('\n\n') + '\n');
  console.log(`kept ${kept} @font-face blocks, ${seen.size} unique woff2 files`);
  console.log(`wrote ${path.relative(ROOT, CSS_OUT)}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
